FROM openjdk:17-jdk-slim

# 환경변수파일 복사
COPY src/main/resources/application.properties application.properties

# 생성된 JAR 파일을 컨테이너 내로 복사
COPY module-batch/build/libs/*.jar app.jar

# wait-for-it.sh 복사 및 스크립트에 실행 권한 부여
COPY wait-for-it.sh /wait-for-it.sh
RUN chmod +x /wait-for-it.sh

# DB 서비스가 시작될 때까지 대기 후 애플리케이션 실행
ENTRYPOINT ["/wait-for-it.sh", "db-mysql.cf0es2youlrz.us-east-1.rds.amazonaws.com:3306", "--", "java", "-Dspring.config.location=file:application.properties", "-jar", "app.jar"]
